
[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/policies(.*)"
secure = "true"
http_method = "GET"
scopes = ["internal_entitlement_policy_mgt_view"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/policies(.*)"
secure = "true"
http_method = "POST"
scopes = ["internal_entitlement_policy_mgt_create"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/policies(.*)"
secure = "true"
http_method = "PATCH"
scopes = ["internal_entitlement_policy_mgt_update"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/policies(.*)"
secure = "true"
http_method = "DELETE"
scopes = ["internal_entitlement_policy_mgt_delete"]

# Entitlement Subscriber API
[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/subscribers(.*)"
secure = "true"
http_method = "GET"
scopes = ["internal_entitlement_subscriber_mgt_view"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/subscribers(.*)"
secure = "true"
http_method = "POST"
scopes = ["internal_entitlement_subscriber_mgt_create"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/subscribers(.*)"
secure = "true"
http_method = "PATCH"
scopes = ["internal_entitlement_subscriber_mgt_update"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/subscribers(.*)"
secure = "true"
http_method = "DELETE"
scopes = ["internal_entitlement_subscriber_mgt_delete"]

# Entitlement Policy Publish API
[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/publish(.*)"
secure = "true"
http_method = "POST"
scopes = ["internal_entitlement_policy_publish"]

# Entitlement Global Policy Combining Algorithm API
[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/combining-algorithm(.*)"
secure = "true"
http_method = "GET"
scopes = ["internal_entitlement_gpa_get"]

[[resource.access_control]]
context = "(.*)/api/identity/entitlement/v1/entitlements/combining-algorithm(.*)"
secure = "true"
http_method = "PATCH"
scopes = ["internal_entitlement_gpa_set"]

[[api_resources]]
name = "Entitlement Policies API"
identifier = "/api/identity/entitlement/v1/entitlements/policies"
requiresAuthorization = true
description = "API representation of the Entitlements Policy Management API"
type = "TENANT"

[[api_resources.scopes]]
displayName = "Create Policy"
name = "internal_entitlement_policy_mgt_create"
description = "Create new Policy"

[[api_resources.scopes]]
displayName = "Update Policy"
name = "internal_entitlement_policy_mgt_update"
description = "Update Policy"

[[api_resources.scopes]]
displayName = "View Policy"
name = "internal_entitlement_policy_mgt_view"
description = "View Policy"

[[api_resources.scopes]]
displayName = "Delete Policy"
name = "internal_entitlement_policy_mgt_delete"
description = "Delete Policy"

[[api_resources]]
name = "Entitlement Subscriber API"
identifier = "/api/identity/entitlement/v1/entitlements/subscribers"
requiresAuthorization = true
description = "API representation of the Entitlement Subscriber Management API"
type = "TENANT"

[[api_resources.scopes]]
displayName = "Create Subscriber"
name = "internal_entitlement_subscriber_mgt_create"
description = "Create new Subscriber"

[[api_resources.scopes]]
displayName = "Update Subscriber"
name = "internal_entitlement_subscriber_mgt_update"
description = "Update Subscriber"

[[api_resources.scopes]]
displayName = "View Subscriber"
name = "internal_entitlement_subscriber_mgt_view"
description = "View Subscriber"

[[api_resources.scopes]]
displayName = "Delete Subscriber"
name = "internal_entitlement_subscriber_mgt_delete"
description = "Delete Subscriber"

[[api_resources]]
name = "Entitlement Global Policy Combining Algorithm API"
identifier = "/api/identity/entitlement/v1/entitlements/combining-algorithm"
requiresAuthorization = true
description = "API representation of the Entitlement Global Policy Combining Algorithm API"
type = "TENANT"

[[api_resources.scopes]]
displayName = "Set Global Policy Combining Algorithm API"
name = "internal_entitlement_gpa_set"
description = "Set Global Policy Combining Algorithm"

[[api_resources.scopes]]
displayName = "Get Global Policy Combining Algorithm API"
name = "internal_entitlement_gpa_get"
description = "Get Global Policy Combining Algorithm"

[[api_resources]]
name = "Entitlement Policy Publish API"
identifier = "/api/identity/entitlement/v1/entitlements/publish"
requiresAuthorization = true
description = "API representation of the Entitlements Policy Publish API"
type = "TENANT"

[[api_resources.scopes]]
displayName = "Publish Policy"
name = "internal_entitlement_policy_publish"
description = "Publish new Policy"

[[event_listener]]
id = "xacml_authorization_handler"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.carbon.identity.application.authz.xacml.handler.impl.XACMLBasedAuthorizationHandler"
order = 899

[identity.entitlement]
entitlement_engine_caching_interval = "1d"
JSON_shorten_form_enabled = false

[identity.entitlement.default_attribute_finder.properties]
MapFederatedUsersToLocal = true

[identity.entitlement.xacml_policy_status]
use_last_status_only = false

[identity.entitlement.policy_point.pdp]
enabled = true
default_caching_interval = "5m"
schema_validation_enabled = true
balana_config_enabled = true
multiple_decision_profile_enabled = true
global_policy_combining_algorithm = "urn:oasis:names:tc:xacml:3.0:policy-combining-algorithm:deny-overrides"
registry_level_policy_cache_clear = false
reference_max_policy_entries = "3000"
policy_finders = ["org.wso2.carbon.identity.entitlement.persistence.JDBCPolicyPersistenceManager"]
policy_store_module = "org.wso2.carbon.identity.entitlement.persistence.JDBCPolicyPersistenceManager"
policy_data_store_module = "org.wso2.carbon.identity.entitlement.policy.store.DefaultPolicyDataStore"

[identity.entitlement.policy_point.pdp.caching.decision_caching]
enabled = true
caching_interval = "$ref{identity.entitlement.policy_point.pdp.default_caching_interval}"

[identity.entitlement.policy_point.pdp.caching.attribute_caching]
enabled = true
caching_interval = "$ref{identity.entitlement.policy_point.pdp.default_caching_interval}"

[identity.entitlement.policy_point.pdp.caching.resource_caching]
enabled = true
caching_interval = "$ref{identity.entitlement.policy_point.pdp.default_caching_interval}"

[identity.entitlement.policy_point.pdp.caching.policy_caching]
caching_interval = "100s"

[identity.entitlement.policy_point.pap]
enabled = true
policy_add_start_enable = true
items_per_page = 10
store_metadata = true
entitlement_data_finders = ["org.wso2.carbon.identity.entitlement.pap.CarbonEntitlementDataFinder"]
policy_publisher_modules = ["org.wso2.carbon.identity.entitlement.policy.publisher.CarbonBasicPolicyPublisherModule"]
status_data_handlers = ["org.wso2.carbon.identity.entitlement.persistence.JDBCSimplePAPStatusDataHandler"]

[identity.entitlement.policy_point.pip]
attribute_designators = [
    "org.wso2.carbon.identity.entitlement.pip.DefaultAttributeFinder",
    "org.wso2.carbon.identity.application.authz.xacml.pip.AuthenticationContextAttributePIP"
]
resource_finders = ["org.wso2.carbon.identity.entitlement.pip.DefaultResourceFinder"]

[oauth.scope_validator.xacml]
enable = true
class = "org.wso2.carbon.identity.oauth2.validators.xacml.XACMLScopeValidator"

[console.policyAdministration]
enabled = "true"

[console.ui]
isXacmlConnectorEnabled = "true"
